### ISSUE TITLE
Please add 1.18.1 support.

### ISSUE THREAD

**Issue by blank826** [MilkBowl/Vault#877] opened 2021-12-28 06:27 UTC

**Comment by Geolykt** [comment] 2021-12-28 10:32
Duplicate of https://github.com/MilkBowl/Vault/issues/876, https://github.com/MilkBowl/Vault/issues/874, https://github.com/MilkBowl/Vault/issues/874, https://github.com/MilkBowl/Vault/issues/873 and https://github.com/MilkBowl/Vault/issues/870

**Closed** 2021-12-28 18:46 UTC
