### ISSUE TITLE
[Vault] Task #15 for Vault v1.6.7-b${env.TRAVIS_BUILD_NUMBER} generated an exception

### ISSUE THREAD

**Issue by andrewkm** [MilkBowl/Vault#720] opened 2018-05-15 17:01 UTC
Just updated to your latest commit:
https://pastebin.com/raw/tPjz3CcW

**Comment by Sleaker** [comment] 2018-05-15 17:35
there was no code-level change in the last commit... This is a pre-existing issue with your permission manager that doesn't work properly with bukkit scheduled tasks.

Looks like it's being generated from luckperms:  me.lucko.luckperms.bukkit.model.permissible.MonitoredPermissibleBase.recalculatePermissions(MonitoredPermissibleBase.java:132)

**Comment by Sleaker** [comment] 2018-05-15 17:38
Closing as duplicate of #719

**Closed by Sleaker** 2018-05-15 17:38 UTC
