### ISSUE TITLE
Vault 1.5.2 - com/earth2me/essentials/OfflinePlayer - Class not Defined.

### ISSUE THREAD

**Issue by Chozo4** [MilkBowl/Vault#588] opened 2015-01-02 04:07 UTC
It seems the update was build on MD_5's EcoCityCraft Jenkins (http://ci.ecocitycraft.com/job/Vault/9/) as version 1.5.1. The null Chat class issue is resolved at least but now the offlineplayer class is not defined.

[22:40:46] [Server thread/WARN]: [Buscript] Task #23 for Buscript v1.1-b28 generated an exception
java.lang.NoClassDefFoundError: com/earth2me/essentials/OfflinePlayer
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_25]
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_25]
	at java.lang.Class.getMethods(Unknown Source) ~[?:1.8.0_25]
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:346) ~[?:?]
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:302) ~[?:?]
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:419) ~[?:?]
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:43) ~[?:?]
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:807) ~[?:?]
	at org.mozilla.javascript.NativeJavaObject.initMembers(NativeJavaObject.java:54) ~[?:?]
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:44) ~[?:?]
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:34) ~[?:?]
	at org.mozilla.javascript.WrapFactory.wrapAsJavaObject(WrapFactory.java:115) ~[?:?]
	at org.mozilla.javascript.WrapFactory.wrap(WrapFactory.java:72) ~[?:?]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:236) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1._c_script_0(plugins\Buscript\startup-script.txt:30) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1.call(plugins\Buscript\startup-script.txt) ~[?:?]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) ~[?:?]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1.call(plugins\Buscript\startup-script.txt) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1.exec(plugins\Buscript\startup-script.txt) ~[?:?]
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1110) ~[?:?]
	at buscript.Buscript.runScript(Buscript.java:677) ~[?:?]
	at buscript.Buscript.executeScript(Buscript.java:539) ~[?:?]
	at buscript.Buscript.executeScript(Buscript.java:505) ~[?:?]
	at buscript.BuscriptPlugin$1.run(BuscriptPlugin.java:27) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: com.earth2me.essentials.OfflinePlayer
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	... 34 more

**Comment by Sleaker** [comment] 2015-01-04 06:11
Please get the official download from http://dev.bukkit.org/plugins/vault - I can't support random builds from md_5's service.

**Comment by Chozo4** [comment] 2015-01-11 21:08
Re-opening this issue as the issue persists in version 1.5.2 which has been officially released.
[16:02:34] [Server thread/WARN]: [Buscript] Task #13 for Buscript v1.1-b28 generated an exception
java.lang.NoClassDefFoundError: com/earth2me/essentials/OfflinePlayer
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693) ~[?:1.8.0_25]
	at java.lang.Class.privateGetPublicMethods(Class.java:2894) ~[?:1.8.0_25]
	at java.lang.Class.getMethods(Class.java:1607) ~[?:1.8.0_25]
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:346) ~[?:?]
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:302) ~[?:?]
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:419) ~[?:?]
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:43) ~[?:?]
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:807) ~[?:?]
	at org.mozilla.javascript.NativeJavaObject.initMembers(NativeJavaObject.java:54) ~[?:?]
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:44) ~[?:?]
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:34) ~[?:?]
	at org.mozilla.javascript.WrapFactory.wrapAsJavaObject(WrapFactory.java:115) ~[?:?]
	at org.mozilla.javascript.WrapFactory.wrap(WrapFactory.java:72) ~[?:?]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:236) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1._c_script_0(plugins\Buscript\startup-script.txt:30) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1.call(plugins\Buscript\startup-script.txt) ~[?:?]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) ~[?:?]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1.call(plugins\Buscript\startup-script.txt) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1.exec(plugins\Buscript\startup-script.txt) ~[?:?]
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1110) ~[?:?]
	at buscript.Buscript.runScript(Buscript.java:677) ~[?:?]
	at buscript.Buscript.executeScript(Buscript.java:539) ~[?:?]
	at buscript.Buscript.executeScript(Buscript.java:505) ~[?:?]
	at buscript.BuscriptPlugin$1.run(BuscriptPlugin.java:27) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: com.earth2me.essentials.OfflinePlayer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 34 more

**Comment by Sleaker** [comment] 2015-01-12 00:48
This does not appear to be a Vault issue. nowhere in here does it say that the issue is being triggered by Vault. Furthermore, Essentials is no longer receiving updates for 1.8 to my knowledge.

**Comment by Chozo4** [comment] 2015-01-12 21:50
I thought it was a vault related issue as the issue only began with version 1.5.x and did not exist with 1.4.x. I do not use essentials however but vault itself is importing the class under Vault/src/net/milkbowl/vault/chat/plugins/Chat_PermissionsEx.java

"import com.earth2me.essentials.OfflinePlayer;"

**Comment by Sleaker** [comment] 2015-01-13 16:27
Ahh, thanks for narrowing down the issue. I'll get this resolved.

**Comment by Sleaker** [comment] 2015-01-13 16:30
Fixed in 1.5.3

**Closed by Sleaker** 2015-01-13 16:30 UTC
